# Generated by Django 2.2 on 2019-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user_pics', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='описание'),
        ),
    ]
