# Generated by Django 2.2 on 2019-11-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191104_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='team',
            name='finish_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оканчание'),
        ),
    ]
