# Generated by Django 2.2 on 2019-10-04 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuetracker',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='кратраткое описание'),
        ),
        migrations.AlterField(
            model_name='issuetracker',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_type', to='webapp.Type', verbose_name='Тип'),
        ),
    ]
