# Generated by Django 2.2 on 2019-10-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191010_0709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_pj',
            new_name='description_project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name_pj',
            new_name='name_project',
        ),
    ]
