# Generated by Django 2.2 on 2019-11-05 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_auto_20191011_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuetracker',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuetracker',
            name='created_by',
            field=models.ForeignKey(default=webapp.models.get_admin, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
