# Generated by Django 2.2 on 2019-11-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20191105_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuetracker',
            old_name='Project',
            new_name='project',
        ),
    ]
