# Generated by Django 2.2 on 2019-11-07 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_auto_20191107_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(verbose_name='Started')),
                ('finished_at', models.DateField(verbose_name='Finished')),
                ('project_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to='webapp.Project', verbose_name='projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team', to=settings.AUTH_USER_MODEL, verbose_name='Users in team')),
            ],
        ),
    ]
