# Generated by Django 2.2 on 2019-11-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
